import sys
from collections import defaultdict
s = 'GATTCATCTTCGACTAAAGTACCCTTCGACTAATCGACTAAGATTCATCTGATTCATCTAGTACCCTCGCGGGCTCGACTAATCGACTAAAGTACCCTGATTCATCTCGCGGGCAGTACCCTGATTCATCTGATTCATCTGATTCATCTTCGACTAAGATTCATCTAGTACCCTAGTGCCGAGTGCCGCGCGGGCAGTACCCTTCGACTAATCGACTAACGCGGGCTCGACTAAAGTACCCTTCGACTAATCGACTAAAGTGCCGCGCGGGCAGTGCCGCGCGGGCAGTACCCTTCGACTAAGATTCATCTGATTCATCTCGCGGGCTCGACTAACGCGGGCTCGACTAACGCGGGCGATTCATCTAGTACCCTAGTACCCTCGCGGGCCGCGGGCAGTGCCGAGTACCCTGATTCATCTAGTACCCTTCGACTAAAGTGCCGGATTCATCTCGCGGGCGATTCATCTGATTCATCTTCGACTAACGCGGGCTCGACTAATCGACTAAGATTCATCTAGTACCCTAGTACCCTAGTGCCGAGTACCCTTCGACTAAAGTGCCGCGCGGGCCGCGGGCAGTGCCGGATTCATCTCGCGGGCTCGACTAAAGTGCCGAGTACCCTAGTGCCGTCGACTAATCGACTAAAGTACCCTAGTACCCTCGCGGGCCGCGGGCAGTGCCGTCGACTAAAGTGCCGTCGACTAAAGTGCCGAGTGCCGGATTCATCTCGCGGGCAGTGCCGTCGACTAACGCGGGCAGTGCCGCGCGGGCTCGACTAAAGTACCCTGATTCATCTAGTACCCTGATTCATCTAGTGCCGAGTACCCTAGTACCCTGATTCATCT'
d = defaultdict(int)
k = 14
l = len(s)
for i in range(l-k+1):
	d[s[i:i+k]] = d[s[i:i+k]] + 1
value = -1
keys = []
for i in d.keys():
	if value < d[i]:
		keys = []
		keys.append(i)
		value = d[i]
	elif value == d[i]:
		keys.append(i)
for i in keys:
	print i,