s = "ACACACCAGAGATGATAATCCGATTAGGGTGTTCGCCCCAAGCACGGCCATAACCGCTTTGACCCGGGGTCACGGACACGCGTACCCTGTGGCACTGCAGACCTTATCTGACCCGTATCGAATGTGTTGAGCATCGGCTTGCCCAGGGTAACGCAATCCCTCGAGTGCGCTTAATACGCCGGATGCGGGTAGTCTCGTAGAGCAACCCTGACCACTCTCTATTTGCCAACCGCCACAGGTAGTTCTTAATGAGGTTCAAGACGCCTTAATATGTTGATGTCCGGTAGTTACGCCCACGCGGGCGGATTCCTTTACGCAAATTTATCTTCTTGCCGCTAAGCCCGCAAAGCCTCCGGACCGCGTCCAGCGCGCTTCACATCCGACCGCGTGCTTATTACCCACACGGCTTTCTATCTTGCCCGCCTGTCATCCAATAGTGGTCGATACGCACTTCGTGGCCCAGGACACGTCTCGAACCTGATACTTCAATCGGAAGCACAACTGAATCTTGTACGTTAGCCGTAAAAACATCATTATCTCAATTGCCGACGGTTGTCCCTCCCCCCATCCCAAAGACGTTACATCGGGCGTGTCGGCCCAGTTCACGCTTCGTGCGGTGGTAGGCTGGCGGTAGTTATGTCCCATCGATTCGCGCACGATTGGTGTGTGCGTTTGATGTTACGTTGTGGTACGGTGGAACCAGTGGATCTCTGACCACGTAATTGTACTGTCATCCGTTGTTTTGATTGCTTGAGGCGAAGGGCCAAAGCCGTTATAGTCACCCTCGGTTTTCTCGACCTTTTTCTAGAGAGCATCGGTACGTCCTGCTACAGTAGAGCAATGGTGCCGCATCTGACAGGATCCCTCCATGTACTTTAGCGAACTACCGTTTTGTCCATGTGAGGGATTAGATCTTGGAAA"
a = []
_s = ""
for i in range(0, len(s)):
    if s[i] == 'A': a.append('T')
    if s[i] == 'C': a.append('G')
    if s[i] == 'G': a.append('C')
    if s[i] == 'T': a.append('A')
print(a)
a.reverse()
print(a)
print(_s.join(a))